Cover App Updated
neptune-mutual-blue/cover-fee-calculator pull request #3
Opened 2022-04-29 03:04 UTC by rupak-nm

-  App homepage updated with cover lists
- Used Mock data to show cover lists, whitelist data & payouts data
- Fixed connect wallet styling in the header
- Other styling changes

2022-04-29 14:36 UTC, savinnpm requested changes

2022-04-29 14:36 UTC, savinnpm commented on components/Payouts/PayoutsTable.jsx
> +      `pt-6 pb-2 font-bold font-poppins text-xs text-text-gray uppercase border-b border-b-DAE2EB`,
add "letter-spacing: 0.05em"

2022-04-30 05:25 UTC, rupak-nm commented on components/Payouts/PayoutsTable.jsx
> +      `pt-6 pb-2 font-bold font-poppins text-xs text-text-gray uppercase border-b border-b-DAE2EB`,
Done

2022-05-02 05:56 UTC, savinnpm approved these changes

2022-05-10 07:23 UTC, merged